version: '3'

services: 
  web: 
    build: .
    volumes:
      - '.:/var/www/demo-express-docker'
    ports:
        - "3001:3000"
  mongo:
    image: "mongo:4.0"
    ports:
        - "17017:27017"
    command: mongod